name: opendrop
description: "Cross-platform proximity-based contact sharing application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^12.0.1
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.9+2
  cryptography: ^2.9.0
  pointycastle: ^4.0.0
  nfc_manager: ^4.1.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  animations: ^2.1.1
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  uuid: ^4.5.2
  intl: ^0.20.2
  logger: ^2.6.2
  device_info_plus: ^12.2.0
  workmanager: ^0.9.0+3
  flutter_foreground_task: ^9.1.0
  flutter_local_notifications: ^19.5.0
  flutter_webrtc: ^1.2.1
  dartz: ^0.10.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Italic.ttf
          style: italic

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
